### ISSUE TITLE
ReflectionHelper throw stackoverflow exception on self reference entities

### ISSUE THREAD

**Issue by MehdiSaeedifar** [VahidN/jqGrid-Samples#1]
I think ParentRole  in Role entity cause infinite loop in ReflectionHelper.FindFieldType method.

```
    public class User
    {
        public string UserName { get; set; }

        public Role Role  { get; set; }
    }
```

```
    public class Role
    {
        public Role ParentRole { get; set; }

        public string Name { get; set; }
    }
```

`ReflectionHelper.FindFieldType(typeof(User), "Role.Name");`

**Comment by VahidN** [comment]
[It's fixed now](https://github.com/VahidN/jqGrid-Samples/commit/c1355d89454b017c20bb0745e9504000fc6978ae#diff-c3f166d2f2d2c870e99e776892faeb91).

**Comment by MehdiSaeedifar** [comment]
I think this line cause stackoverflow exception again.

`property.PropertyType.Name.Equals(parent.TrimEnd('.')))`

and should change to this

`property.Name.Equals(parent.TrimEnd('.')))`
